// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTags(arg1, arg2) {
  return window['go']['main']['App']['ApplyTags'](arg1, arg2);
}

export function CreateTag(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function GetFileTags(arg1) {
  return window['go']['main']['App']['GetFileTags'](arg1);
}

export function GetFilteredFiles(arg1) {
  return window['go']['main']['App']['GetFilteredFiles'](arg1);
}

export function GetInboxPath() {
  return window['go']['main']['App']['GetInboxPath']();
}

export function GetMediaBaseURL() {
  return window['go']['main']['App']['GetMediaBaseURL']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function ScanInbox(arg1, arg2) {
  return window['go']['main']['App']['ScanInbox'](arg1, arg2);
}

export function SetInboxPath(arg1) {
  return window['go']['main']['App']['SetInboxPath'](arg1);
}

export function TrashFile(arg1) {
  return window['go']['main']['App']['TrashFile'](arg1);
}

export function UpdateTag(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateTag'](arg1, arg2, arg3, arg4, arg5, arg6);
}
