// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ApplyTags(arg1:string,arg2:Array<number>):Promise<model.ApplyResult>;

export function CreateTag(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<model.Tag>;

export function DeleteTag(arg1:number):Promise<void>;

export function GetFileTags(arg1:string):Promise<Array<model.Tag>>;

export function GetFilteredFiles(arg1:Array<number>):Promise<Array<string>>;

export function GetInboxPath():Promise<string>;

export function GetMediaBaseURL():Promise<string>;

export function GetTags():Promise<Array<model.Tag>>;

export function OpenDirectoryDialog():Promise<string>;

export function ScanInbox(arg1:boolean,arg2:string):Promise<Array<model.FileInfo>>;

export function SetInboxPath(arg1:string):Promise<void>;

export function TrashFile(arg1:string):Promise<void>;

export function UpdateTag(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;
